# Generated by Django 4.0.1 on 2022-11-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.TextField(default=None)),
                ('receiver', models.TextField(default=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.TextField(default=None)),
                ('user_mail', models.TextField(default=None)),
                ('valid_until', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TopicList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.TextField(default=None)),
                ('title', models.TextField(default=None)),
                ('message', models.TextField(default=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('anonymous', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopicsMsg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idTopic', models.IntegerField(default=None)),
                ('author', models.TextField(default=None)),
                ('message', models.TextField(default=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('edited', models.BooleanField(default=False)),
            ],
        ),
    ]
